### ISSUE TITLE
Cache Buster: URL Parameters for the SAP Fiori Launchpad

### ISSUE THREAD

**Issue by lboehm** [hdrpknc/Reference-work#1]
https://help.sap.com/viewer/a7b390faab1140c087b8926571e942b7/7.4.19/en-US/a1e56ed27d2f48b8bfed95bd80a23d88.html

**Comment by hdrpknc** [comment]
iam on it 👍

**Comment by lboehm** [comment]
Perfect. Can't wait.

**Comment by hdrpknc** [comment]
done :) https://github.com/hdrpknc/Reference-work/blob/master/ui5_development.md#url-parameter

thanks for your contribution
